# Exploring ENDF/B-VIII.1

<!-- index:description -->
Explore `cross_section.xml` and HDF5 data from ENDF/B-VIII.1,
comparing direct XML/HDF5 inspection with the OpenMC Python API.
<!-- /index:description -->

<!-- generated:structure -->
```text
Exploring ENDF/B-VIII.1
├── Directory structure
├── Look inside `cross_sections.xml`
│   ├── 1. Manual parsing
│   ├── 2. Using XML parser
│   ├── 3. Using OpenMC
│   └── Comparison of the three XML interfaces
├── Look inside `HDF5` files
│   ├── Using `h5py`
│   ├── Using openmc.data.IncidentNeutron.from_hdf5()
│   └── Interpretation of MT numbers
└── Materials × MT availability
```
<!-- /generated:structure -->

The data location is configured in [openmc_workbench_config.py](../openmc_workbench_config.py). Before running this notebook, install the shared module into your Jupyter kernel’s Python environment: run `%pip install -e /absolute/path/to/openmc-workbench` in a notebook cell, replacing the path with your repository checkout. The default installation is `~/data`; edit `DATA_ROOT` in the shared module to use another location. Restart the kernel after changing the configuration.

**Scope of this notebook**

This notebook explores how OpenMC nuclear-data libraries are organized and accessed, both directly through their underlying XML/HDF5 files and through the OpenMC Python API.

Imports are introduced at the point of use to highlight the dependencies specific to each plotting approach.

The manual methods are included for **exploratory and educational purposes**, to expose the underlying file structures and illustrate how the higher-level interfaces work. They are not intended as production implementations.

For production applications, prefer established parsers and the OpenMC API, which provide better abstraction, validation, and compatibility with supported data formats. Direct access to XML/HDF5 remains appropriate when the task specifically requires inspecting or manipulating the underlying data structures.

## Directory structure

In [1]:
from pathlib import Path

from openmc_workbench_config import ENDF_B81

nuc_dat_path = ENDF_B81
assert nuc_dat_path.is_dir()
for tis in Path(nuc_dat_path).iterdir():
    if tis.is_file():
        print(tis)
# Top-level directory contains just a xml file

../../data/endf-b8.1/cross_sections.xml

This will be the argument for [openmc.data.DataLibrary.from_xml()](https://docs.openmc.org/en/stable/pythonapi/generated/openmc.data.DataLibrary.html#openmc.data.DataLibrary).

Assign it to `xs_xml`.

In [2]:
xs_xml = nuc_dat_path / 'cross_sections.xml'
assert xs_xml.is_file()

`cross_sections.xml` reminds me of MCNP's `xsdir`: they provide index lookup.

|                      | MCNP's xsdir              | OpenMC's cross_sections.xml |
| --- | --- | --- |
| Index file             | `xsdir`                   | `cross_sections.xml` |
| Index format           | Plain text                | XML |
| Nuclear-data format    | ACE                       | HDF5 |
| Nuclide identification | ZAID                      | `materials` attribute | 
| Data type              | ZAID suffix e.g. `.80c` | `type` attribute |

In [3]:
for tis in Path(nuc_dat_path).iterdir():
    if tis.is_dir():
        print(tis)
# Top-level directory contains these subdirectories.

../../data/endf-b8.1/thermal
../../data/endf-b8.1/neutron
../../data/endf-b8.1/photon

In [4]:
max_file_depth = 0
for path in nuc_dat_path.rglob('*'):
    if path.is_file():
        depth = len(path.relative_to(nuc_dat_path).parts)
        max_file_depth = max(max_file_depth, depth)
max_file_depth

2

## Look inside `cross_sections.xml`

Ways of looking inside:
1. manual parsing line by line;
2. using XML parser `xml.etree.ElementTree`;
3. using OpenMC.

### 1. Manual parsing
The regular expression relies on XML attribute order and whitespace; this is intentional manual parsing.

In [5]:
import re
import pandas as pd          # Hard to live without pandas as an ML person.

xs_manual = []               # This will become a dataframe when loop exits, just borrowing a list's efficiency.
with open(xs_xml) as fp:
    lines = fp.read().splitlines()
    for nline, line in enumerate(lines):
        match = re.search(
            r'  <library materials="(.*)" path="(.*)" type="(.*)" />',
            line
        )
        
        if match:
            xs_manual.append(match.groups())
        else:
            print(f'{nline}/{len(lines)}', line)

xs_manual = pd.DataFrame(xs_manual, columns=['materials', 'path', 'type'])
assert (                                        # `type` consistently agrees with the subdirectory name: no surprises.
    xs_manual['path'].map(lambda x: Path(x).parts[0])
    == xs_manual['type']
).all() 
xs_manual
# Apart from the header row, and the start and end `cross_sections` tags,
# all remaining rows have the same pattern: <library materials=... path=... type=.../>.

0/771 <?xml version='1.0' encoding='utf-8'?>
1/771 <cross_sections>
770/771 </cross_sections>

    materials            path     type
0          H1   neutron/H1.h5  neutron
1          H2   neutron/H2.h5  neutron
2          H3   neutron/H3.h5  neutron
3         He3  neutron/He3.h5  neutron
4         He4  neutron/He4.h5  neutron
..        ...             ...      ...
763        Cm    photon/Cm.h5   photon
764        Bk    photon/Bk.h5   photon
765        Cf    photon/Cf.h5   photon
766        Es    photon/Es.h5   photon
767        Fm    photon/Fm.h5   photon

[768 rows x 3 columns]

In [6]:
assert xs_manual['path'].map(lambda x: (nuc_dat_path / x).is_file()).all()
# Every single entry corresponds to an HDF5 file (extension `.h5`) in the respective subdirectory.

### 2. Using XML parser

In [7]:
import xml.etree.ElementTree as ET

root = ET.parse(xs_xml).getroot()

xs_etree = pd.DataFrame([
    element.attrib
    for element in root.findall('library')
])

### 3. Using OpenMC

In [8]:
import openmc

library = openmc.data.DataLibrary.from_xml(xs_xml)
for tis in library.libraries:
    assert isinstance(tis, dict)
    assert {'materials', 'path', 'type'} <= tis.keys()
# Consistent with what we found when looking inside the xml: 
# it contains simple length-of-three dictionaries. No nesting.
library.libraries

[{'path': '../../data/endf-b8.1/neutron/H1.h5',
  'type': 'neutron',
  'materials': ['H1']},
 {'path': '../../data/endf-b8.1/neutron/H2.h5',
  'type': 'neutron',
  'materials': ['H2']},
 {'path': '../../data/endf-b8.1/neutron/H3.h5',
  'type': 'neutron',
  'materials': ['H3']},
 {'path': '../../data/endf-b8.1/neutron/He3.h5',
  'type': 'neutron',
  'materials': ['He3']},
 {'path': '../../data/endf-b8.1/neutron/He4.h5',
  'type': 'neutron',
  'materials': ['He4']},
 {'path': '../../data/endf-b8.1/neutron/Li6.h5',
  'type': 'neutron',
  'materials': ['Li6']},
 {'path': '../../data/endf-b8.1/neutron/Li7.h5',
  'type': 'neutron',
  'materials': ['Li7']},
 {'path': '../../data/endf-b8.1/neutron/Be7.h5',
  'type': 'neutron',
  'materials': ['Be7']},
 {'path': '../../data/endf-b8.1/neutron/Be9.h5',
  'type': 'neutron',
  'materials': ['Be9']},
 {'path': '../../data/endf-b8.1/neutron/B10.h5',
  'type': 'neutron',
  'materials': ['B10']},
 {'path': '../../data/endf-b8.1/neutron/B11.h5',
  'type': 'neutron',
  'materials': ['B11']},
 {'path': '../../data/endf-b8.1/neutron/C12.h5',
  'type': 'neutron',
  'materials': ['C12']},
 {'path': '../../data/endf-b8.1/neutron/C13.h5',
  'type': 'neutron',
  'materials': ['C13']},
 {'path': '../../data/endf-b8.1/neutron/N14.h5',
  'type': 'neutron',
  'materials': ['N14']},
 {'path': '../../data/endf-b8.1/neutron/N15.h5',
  'type': 'neutron',
  'materials': ['N15']},
 {'path': '../../data/endf-b8.1/neutron/O16.h5',
  'type': 'neutron',
  'materials': ['O16']},
 {'path': '../../data/endf-b8.1/neutron/O17.h5',
  'type': 'neutron',
  'materials': ['O17']},
 {'path': '../../data/endf-b8.1/neutron/O18.h5',
  'type': 'neutron',
  'materials': ['O18']},
 {'path': '../../data/endf-b8.1/neutron/F19.h5',
  'type': 'neutron',
  'materials': ['F19']},
 {'path': '../../data/endf-b8.1/neutron/Ne20.h5',
  'type': 'neutron',
  'materials': ['Ne20']},
 {'path': '../../data/endf-b8.1/neutron/Ne21.h5',
  'type': 'neutron',
  'materials': ['Ne21']},
 {'path': '../../data/endf-b8.1/neutron/Ne22.h5',
  'type': 'neutron',
  'materials': ['Ne22']},
 {'path': '../../data/endf-b8.1/neutron/Na22.h5',
  'type': 'neutron',
  'materials': ['Na22']},
 {'path': '../../data/endf-b8.1/neutron/Na23.h5',
  'type': 'neutron',
  'materials': ['Na23']},
 {'path': '../../data/endf-b8.1/neutron/Mg24.h5',
  'type': 'neutron',
  'materials': ['Mg24']},
 {'path': '../../data/endf-b8.1/neutron/Mg25.h5',
  'type': 'neutron',
  'materials': ['Mg25']},
 {'path': '../../data/endf-b8.1/neutron/Mg26.h5',
  'type': 'neutron',
  'materials': ['Mg26']},
 {'path': '../../data/endf-b8.1/neutron/Al26_m1.h5',
  'type': 'neutron',
  'materials': ['Al26_m1']},
 {'path': '../../data/endf-b8.1/neutron/Al27.h5',
  'type': 'neutron',
  'materials': ['Al27']},
 {'path': '../../data/endf-b8.1/neutron/Si28.h5',
  'type': 'neutron',
  'materials': ['Si28']},
 {'path': '../../data/endf-b8.1/neutron/Si29.h5',
  'type': 'neutron',
  'materials': ['Si29']},
 {'path': '../../data/endf-b8.1/neutron/Si30.h5',
  'type': 'neutron',
  'materials': ['Si30']},
 {'path': '../../data/endf-b8.1/neutron/Si31.h5',
  'type': 'neutron',
  'materials': ['Si31']},
 {'path': '../../data/endf-b8.1/neutron/Si32.h5',
  'type': 'neutron',
  'materials': ['Si32']},
 {'path': '../../data/endf-b8.1/neutron/P31.h5',
  'type': 'neutron',
  'materials': ['P31']},
 {'path': '../../data/endf-b8.1/neutron/S32.h5',
  'type': 'neutron',
  'materials': ['S32']},
 {'path': '../../data/endf-b8.1/neutron/S33.h5',
  'type': 'neutron',
  'materials': ['S33']},
 {'path': '../../data/endf-b8.1/neutron/S34.h5',
  'type': 'neutron',
  'materials': ['S34']},
 {'path': '../../data/endf-b8.1/neutron/S35.h5',
  'type': 'neutron',
  'materials': ['S35']},
 {'path': '../../data/endf-b8.1/neutron/S36.h5',
  'type': 'neutron',
  'materials': ['S36']},
 {'path': '../../data/endf-b8.1/neutron/Cl35.h5',
  'type': 'neutron',
  'materials': ['Cl35']},
 {'path': '../../data/endf-b8.1/neutron/Cl36.h5',
  'type': 'neutron',
  'materials': ['Cl36']},
 {'path': '../../data/endf-b8.1/neutron/Cl37.h5',
  'type': 'neutron',
  'materials': ['Cl37']},
 {'path': '../../data/endf-b8.1/neutron/Ar36.h5',
  'type': 'neutron',
  'materials': ['Ar36']},
 {'path': '../../data/endf-b8.1/neutron/Ar37.h5',
  'type': 'neutron',
  'materials': ['Ar37']},
 {'path': '../../data/endf-b8.1/neutron/Ar38.h5',
  'type': 'neutron',
  'materials': ['Ar38']},
 {'path': '../../data/endf-b8.1/neutron/Ar39.h5',
  'type': 'neutron',
  'materials': ['Ar39']},
 {'path': '../../data/endf-b8.1/neutron/Ar40.h5',
  'type': 'neutron',
  'materials': ['Ar40']},
 {'path': '../../data/endf-b8.1/neutron/Ar41.h5',
  'type': 'neutron',
  'materials': ['Ar41']},
 {'path': '../../data/endf-b8.1/neutron/K39.h5',
  'type': 'neutron',
  'materials': ['K39']},
 {'path': '../../data/endf-b8.1/neutron/K40.h5',
  'type': 'neutron',
  'materials': ['K40']},
 {'path': '../../data/endf-b8.1/neutron/K41.h5',
  'type': 'neutron',
  'materials': ['K41']},
 {'path': '../../data/endf-b8.1/neutron/Ca40.h5',
  'type': 'neutron',
  'materials': ['Ca40']},
 {'path': '../../data/endf-b8.1/neutron/Ca41.h5',
  'type': 'neutron',
  'materials': ['Ca41']},
 {'path': '../../data/endf-b8.1/neutron/Ca42.h5',
  'type': 'neutron',
  'materials': ['Ca42']},
 {'path': '../../data/endf-b8.1/neutron/Ca43.h5',
  'type': 'neutron',
  'materials': ['Ca43']},
 {'path': '../../data/endf-b8.1/neutron/Ca44.h5',
  'type': 'neutron',
  'materials': ['Ca44']},
 {'path': '../../data/endf-b8.1/neutron/Ca45.h5',
  'type': 'neutron',
  'materials': ['Ca45']},
 {'path': '../../data/endf-b8.1/neutron/Ca46.h5',
  'type': 'neutron',
  'materials': ['Ca46']},
 {'path': '../../data/endf-b8.1/neutron/Ca47.h5',
  'type': 'neutron',
  'materials': ['Ca47']},
 {'path': '../../data/endf-b8.1/neutron/Ca48.h5',
  'type': 'neutron',
  'materials': ['Ca48']},
 {'path': '../../data/endf-b8.1/neutron/Sc45.h5',
  'type': 'neutron',
  'materials': ['Sc45']},
 {'path': '../../data/endf-b8.1/neutron/Ti46.h5',
  'type': 'neutron',
  'materials': ['Ti46']},
 {'path': '../../data/endf-b8.1/neutron/Ti47.h5',
  'type': 'neutron',
  'materials': ['Ti47']},
 {'path': '../../data/endf-b8.1/neutron/Ti48.h5',
  'type': 'neutron',
  'materials': ['Ti48']},
 {'path': '../../data/endf-b8.1/neutron/Ti49.h5',
  'type': 'neutron',
  'materials': ['Ti49']},
 {'path': '../../data/endf-b8.1/neutron/Ti50.h5',
  'type': 'neutron',
  'materials': ['Ti50']},
 {'path': '../../data/endf-b8.1/neutron/V49.h5',
  'type': 'neutron',
  'materials': ['V49']},
 {'path': '../../data/endf-b8.1/neutron/V50.h5',
  'type': 'neutron',
  'materials': ['V50']},
 {'path': '../../data/endf-b8.1/neutron/V51.h5',
  'type': 'neutron',
  'materials': ['V51']},
 {'path': '../../data/endf-b8.1/neutron/Cr50.h5',
  'type': 'neutron',
  'materials': ['Cr50']},
 {'path': '../../data/endf-b8.1/neutron/Cr51.h5',
  'type': 'neutron',
  'materials': ['Cr51']},
 {'path': '../../data/endf-b8.1/neutron/Cr52.h5',
  'type': 'neutron',
  'materials': ['Cr52']},
 {'path': '../../data/endf-b8.1/neutron/Cr53.h5',
  'type': 'neutron',
  'materials': ['Cr53']},
 {'path': '../../data/endf-b8.1/neutron/Cr54.h5',
  'type': 'neutron',
  'materials': ['Cr54']},
 {'path': '../../data/endf-b8.1/neutron/Mn54.h5',
  'type': 'neutron',
  'materials': ['Mn54']},
 {'path': '../../data/endf-b8.1/neutron/Mn55.h5',
  'type': 'neutron',
  'materials': ['Mn55']},
 {'path': '../../data/endf-b8.1/neutron/Fe54.h5',
  'type': 'neutron',
  'materials': ['Fe54']},
 {'path': '../../data/endf-b8.1/neutron/Fe55.h5',
  'type': 'neutron',
  'materials': ['Fe55']},
 {'path': '../../data/endf-b8.1/neutron/Fe56.h5',
  'type': 'neutron',
  'materials': ['Fe56']},
 {'path': '../../data/endf-b8.1/neutron/Fe57.h5',
  'type': 'neutron',
  'materials': ['Fe57']},
 {'path': '../../data/endf-b8.1/neutron/Fe58.h5',
  'type': 'neutron',
  'materials': ['Fe58']},
 {'path': '../../data/endf-b8.1/neutron/Co58.h5',
  'type': 'neutron',
  'materials': ['Co58']},
 {'path': '../../data/endf-b8.1/neutron/Co58_m1.h5',
  'type': 'neutron',
  'materials': ['Co58_m1']},
 {'path': '../../data/endf-b8.1/neutron/Co59.h5',
  'type': 'neutron',
  'materials': ['Co59']},
 {'path': '../../data/endf-b8.1/neutron/Ni58.h5',
  'type': 'neutron',
  'materials': ['Ni58']},
 {'path': '../../data/endf-b8.1/neutron/Ni59.h5',
  'type': 'neutron',
  'materials': ['Ni59']},
 {'path': '../../data/endf-b8.1/neutron/Ni60.h5',
  'type': 'neutron',
  'materials': ['Ni60']},
 {'path': '../../data/endf-b8.1/neutron/Ni61.h5',
  'type': 'neutron',
  'materials': ['Ni61']},
 {'path': '../../data/endf-b8.1/neutron/Ni62.h5',
  'type': 'neutron',
  'materials': ['Ni62']},
 {'path': '../../data/endf-b8.1/neutron/Ni63.h5',
  'type': 'neutron',
  'materials': ['Ni63']},
 {'path': '../../data/endf-b8.1/neutron/Ni64.h5',
  'type': 'neutron',
  'materials': ['Ni64']},
 {'path': '../../data/endf-b8.1/neutron/Cu63.h5',
  'type': 'neutron',
  'materials': ['Cu63']},
 {'path': '../../data/endf-b8.1/neutron/Cu64.h5',
  'type': 'neutron',
  'materials': ['Cu64']},
 {'path': '../../data/endf-b8.1/neutron/Cu65.h5',
  'type': 'neutron',
  'materials': ['Cu65']},
 {'path': '../../data/endf-b8.1/neutron/Zn64.h5',
  'type': 'neutron',
  'materials': ['Zn64']},
 {'path': '../../data/endf-b8.1/neutron/Zn65.h5',
  'type': 'neutron',
  'materials': ['Zn65']},
 {'path': '../../data/endf-b8.1/neutron/Zn66.h5',
  'type': 'neutron',
  'materials': ['Zn66']},
 {'path': '../../data/endf-b8.1/neutron/Zn67.h5',
  'type': 'neutron',
  'materials': ['Zn67']},
 {'path': '../../data/endf-b8.1/neutron/Zn68.h5',
  'type': 'neutron',
  'materials': ['Zn68']},
 {'path': '../../data/endf-b8.1/neutron/Zn69.h5',
  'type': 'neutron',
  'materials': ['Zn69']},
 {'path': '../../data/endf-b8.1/neutron/Zn70.h5',
  'type': 'neutron',
  'materials': ['Zn70']},
 {'path': '../../data/endf-b8.1/neutron/Ga69.h5',
  'type': 'neutron',
  'materials': ['Ga69']},
 {'path': '../../data/endf-b8.1/neutron/Ga70.h5',
  'type': 'neutron',
  'materials': ['Ga70']},
 {'path': '../../data/endf-b8.1/neutron/Ga71.h5',
  'type': 'neutron',
  'materials': ['Ga71']},
 {'path': '../../data/endf-b8.1/neutron/Ge70.h5',
  'type': 'neutron',
  'materials': ['Ge70']},
 {'path': '../../data/endf-b8.1/neutron/Ge71.h5',
  'type': 'neutron',
  'materials': ['Ge71']},
 {'path': '../../data/endf-b8.1/neutron/Ge72.h5',
  'type': 'neutron',
  'materials': ['Ge72']},
 {'path': '../../data/endf-b8.1/neutron/Ge73.h5',
  'type': 'neutron',
  'materials': ['Ge73']},
 {'path': '../../data/endf-b8.1/neutron/Ge74.h5',
  'type': 'neutron',
  'materials': ['Ge74']},
 {'path': '../../data/endf-b8.1/neutron/Ge75.h5',
  'type': 'neutron',
  'materials': ['Ge75']},
 {'path': '../../data/endf-b8.1/neutron/Ge76.h5',
  'type': 'neutron',
  'materials': ['Ge76']},
 {'path': '../../data/endf-b8.1/neutron/As73.h5',
  'type': 'neutron',
  'materials': ['As73']},
 {'path': '../../data/endf-b8.1/neutron/As74.h5',
  'type': 'neutron',
  'materials': ['As74']},
 {'path': '../../data/endf-b8.1/neutron/As75.h5',
  'type': 'neutron',
  'materials': ['As75']},
 {'path': '../../data/endf-b8.1/neutron/Se74.h5',
  'type': 'neutron',
  'materials': ['Se74']},
 {'path': '../../data/endf-b8.1/neutron/Se75.h5',
  'type': 'neutron',
  'materials': ['Se75']},
 {'path': '../../data/endf-b8.1/neutron/Se76.h5',
  'type': 'neutron',
  'materials': ['Se76']},
 {'path': '../../data/endf-b8.1/neutron/Se77.h5',
  'type': 'neutron',
  'materials': ['Se77']},
 {'path': '../../data/endf-b8.1/neutron/Se78.h5',
  'type': 'neutron',
  'materials': ['Se78']},
 {'path': '../../data/endf-b8.1/neutron/Se79.h5',
  'type': 'neutron',
  'materials': ['Se79']},
 {'path': '../../data/endf-b8.1/neutron/Se80.h5',
  'type': 'neutron',
  'materials': ['Se80']},
 {'path': '../../data/endf-b8.1/neutron/Se81.h5',
  'type': 'neutron',
  'materials': ['Se81']},
 {'path': '../../data/endf-b8.1/neutron/Se82.h5',
  'type': 'neutron',
  'materials': ['Se82']},
 {'path': '../../data/endf-b8.1/neutron/Br79.h5',
  'type': 'neutron',
  'materials': ['Br79']},
 {'path': '../../data/endf-b8.1/neutron/Br80.h5',
  'type': 'neutron',
  'materials': ['Br80']},
 {'path': '../../data/endf-b8.1/neutron/Br81.h5',
  'type': 'neutron',
  'materials': ['Br81']},
 {'path': '../../data/endf-b8.1/neutron/Kr78.h5',
  'type': 'neutron',
  'materials': ['Kr78']},
 {'path': '../../data/endf-b8.1/neutron/Kr79.h5',
  'type': 'neutron',
  'materials': ['Kr79']},
 {'path': '../../data/endf-b8.1/neutron/Kr80.h5',
  'type': 'neutron',
  'materials': ['Kr80']},
 {'path': '../../data/endf-b8.1/neutron/Kr81.h5',
  'type': 'neutron',
  'materials': ['Kr81']},
 {'path': '../../data/endf-b8.1/neutron/Kr82.h5',
  'type': 'neutron',
  'materials': ['Kr82']},
 {'path': '../../data/endf-b8.1/neutron/Kr83.h5',
  'type': 'neutron',
  'materials': ['Kr83']},
 {'path': '../../data/endf-b8.1/neutron/Kr84.h5',
  'type': 'neutron',
  'materials': ['Kr84']},
 {'path': '../../data/endf-b8.1/neutron/Kr85.h5',
  'type': 'neutron',
  'materials': ['Kr85']},
 {'path': '../../data/endf-b8.1/neutron/Kr86.h5',
  'type': 'neutron',
  'materials': ['Kr86']},
 {'path': '../../data/endf-b8.1/neutron/Rb85.h5',
  'type': 'neutron',
  'materials': ['Rb85']},
 {'path': '../../data/endf-b8.1/neutron/Rb86.h5',
  'type': 'neutron',
  'materials': ['Rb86']},
 {'path': '../../data/endf-b8.1/neutron/Rb87.h5',
  'type': 'neutron',
  'materials': ['Rb87']},
 {'path': '../../data/endf-b8.1/neutron/Sr84.h5',
  'type': 'neutron',
  'materials': ['Sr84']},
 {'path': '../../data/endf-b8.1/neutron/Sr85.h5',
  'type': 'neutron',
  'materials': ['Sr85']},
 {'path': '../../data/endf-b8.1/neutron/Sr86.h5',
  'type': 'neutron',
  'materials': ['Sr86']},
 {'path': '../../data/endf-b8.1/neutron/Sr87.h5',
  'type': 'neutron',
  'materials': ['Sr87']},
 {'path': '../../data/endf-b8.1/neutron/Sr88.h5',
  'type': 'neutron',
  'materials': ['Sr88']},
 {'path': '../../data/endf-b8.1/neutron/Sr89.h5',
  'type': 'neutron',
  'materials': ['Sr89']},
 {'path': '../../data/endf-b8.1/neutron/Sr90.h5',
  'type': 'neutron',
  'materials': ['Sr90']},
 {'path': '../../data/endf-b8.1/neutron/Y89.h5',
  'type': 'neutron',
  'materials': ['Y89']},
 {'path': '../../data/endf-b8.1/neutron/Y90.h5',
  'type': 'neutron',
  'materials': ['Y90']},
 {'path': '../../data/endf-b8.1/neutron/Y91.h5',
  'type': 'neutron',
  'materials': ['Y91']},
 {'path': '../../data/endf-b8.1/neutron/Zr90.h5',
  'type': 'neutron',
  'materials': ['Zr90']},
 {'path': '../../data/endf-b8.1/neutron/Zr91.h5',
  'type': 'neutron',
  'materials': ['Zr91']},
 {'path': '../../data/endf-b8.1/neutron/Zr92.h5',
  'type': 'neutron',
  'materials': ['Zr92']},
 {'path': '../../data/endf-b8.1/neutron/Zr93.h5',
  'type': 'neutron',
  'materials': ['Zr93']},
 {'path': '../../data/endf-b8.1/neutron/Zr94.h5',
  'type': 'neutron',
  'materials': ['Zr94']},
 {'path': '../../data/endf-b8.1/neutron/Zr95.h5',
  'type': 'neutron',
  'materials': ['Zr95']},
 {'path': '../../data/endf-b8.1/neutron/Zr96.h5',
  'type': 'neutron',
  'materials': ['Zr96']},
 {'path': '../../data/endf-b8.1/neutron/Nb93.h5',
  'type': 'neutron',
  'materials': ['Nb93']},
 {'path': '../../data/endf-b8.1/neutron/Nb94.h5',
  'type': 'neutron',
  'materials': ['Nb94']},
 {'path': '../../data/endf-b8.1/neutron/Nb95.h5',
  'type': 'neutron',
  'materials': ['Nb95']},
 {'path': '../../data/endf-b8.1/neutron/Mo92.h5',
  'type': 'neutron',
  'materials': ['Mo92']},
 {'path': '../../data/endf-b8.1/neutron/Mo93.h5',
  'type': 'neutron',
  'materials': ['Mo93']},
 {'path': '../../data/endf-b8.1/neutron/Mo94.h5',
  'type': 'neutron',
  'materials': ['Mo94']},
 {'path': '../../data/endf-b8.1/neutron/Mo95.h5',
  'type': 'neutron',
  'materials': ['Mo95']},
 {'path': '../../data/endf-b8.1/neutron/Mo96.h5',
  'type': 'neutron',
  'materials': ['Mo96']},
 {'path': '../../data/endf-b8.1/neutron/Mo97.h5',
  'type': 'neutron',
  'materials': ['Mo97']},
 {'path': '../../data/endf-b8.1/neutron/Mo98.h5',
  'type': 'neutron',
  'materials': ['Mo98']},
 {'path': '../../data/endf-b8.1/neutron/Mo99.h5',
  'type': 'neutron',
  'materials': ['Mo99']},
 {'path': '../../data/endf-b8.1/neutron/Mo100.h5',
  'type': 'neutron',
  'materials': ['Mo100']},
 {'path': '../../data/endf-b8.1/neutron/Tc98.h5',
  'type': 'neutron',
  'materials': ['Tc98']},
 {'path': '../../data/endf-b8.1/neutron/Tc99.h5',
  'type': 'neutron',
  'materials': ['Tc99']},
 {'path': '../../data/endf-b8.1/neutron/Ru96.h5',
  'type': 'neutron',
  'materials': ['Ru96']},
 {'path': '../../data/endf-b8.1/neutron/Ru97.h5',
  'type': 'neutron',
  'materials': ['Ru97']},
 {'path': '../../data/endf-b8.1/neutron/Ru98.h5',
  'type': 'neutron',
  'materials': ['Ru98']},
 {'path': '../../data/endf-b8.1/neutron/Ru99.h5',
  'type': 'neutron',
  'materials': ['Ru99']},
 {'path': '../../data/endf-b8.1/neutron/Ru100.h5',
  'type': 'neutron',
  'materials': ['Ru100']},
 {'path': '../../data/endf-b8.1/neutron/Ru101.h5',
  'type': 'neutron',
  'materials': ['Ru101']},
 {'path': '../../data/endf-b8.1/neutron/Ru102.h5',
  'type': 'neutron',
  'materials': ['Ru102']},
 {'path': '../../data/endf-b8.1/neutron/Ru103.h5',
  'type': 'neutron',
  'materials': ['Ru103']},
 {'path': '../../data/endf-b8.1/neutron/Ru104.h5',
  'type': 'neutron',
  'materials': ['Ru104']},
 {'path': '../../data/endf-b8.1/neutron/Ru105.h5',
  'type': 'neutron',
  'materials': ['Ru105']},
 {'path': '../../data/endf-b8.1/neutron/Ru106.h5',
  'type': 'neutron',
  'materials': ['Ru106']},
 {'path': '../../data/endf-b8.1/neutron/Rh103.h5',
  'type': 'neutron',
  'materials': ['Rh103']},
 {'path': '../../data/endf-b8.1/neutron/Rh104.h5',
  'type': 'neutron',
  'materials': ['Rh104']},
 {'path': '../../data/endf-b8.1/neutron/Rh105.h5',
  'type': 'neutron',
  'materials': ['Rh105']},
 {'path': '../../data/endf-b8.1/neutron/Pd102.h5',
  'type': 'neutron',
  'materials': ['Pd102']},
 {'path': '../../data/endf-b8.1/neutron/Pd103.h5',
  'type': 'neutron',
  'materials': ['Pd103']},
 {'path': '../../data/endf-b8.1/neutron/Pd104.h5',
  'type': 'neutron',
  'materials': ['Pd104']},
 {'path': '../../data/endf-b8.1/neutron/Pd105.h5',
  'type': 'neutron',
  'materials': ['Pd105']},
 {'path': '../../data/endf-b8.1/neutron/Pd106.h5',
  'type': 'neutron',
  'materials': ['Pd106']},
 {'path': '../../data/endf-b8.1/neutron/Pd107.h5',
  'type': 'neutron',
  'materials': ['Pd107']},
 {'path': '../../data/endf-b8.1/neutron/Pd108.h5',
  'type': 'neutron',
  'materials': ['Pd108']},
 {'path': '../../data/endf-b8.1/neutron/Pd109.h5',
  'type': 'neutron',
  'materials': ['Pd109']},
 {'path': '../../data/endf-b8.1/neutron/Pd110.h5',
  'type': 'neutron',
  'materials': ['Pd110']},
 {'path': '../../data/endf-b8.1/neutron/Ag107.h5',
  'type': 'neutron',
  'materials': ['Ag107']},
 {'path': '../../data/endf-b8.1/neutron/Ag108.h5',
  'type': 'neutron',
  'materials': ['Ag108']},
 {'path': '../../data/endf-b8.1/neutron/Ag109.h5',
  'type': 'neutron',
  'materials': ['Ag109']},
 {'path': '../../data/endf-b8.1/neutron/Ag110_m1.h5',
  'type': 'neutron',
  'materials': ['Ag110_m1']},
 {'path': '../../data/endf-b8.1/neutron/Ag111.h5',
  'type': 'neutron',
  'materials': ['Ag111']},
 {'path': '../../data/endf-b8.1/neutron/Ag112.h5',
  'type': 'neutron',
  'materials': ['Ag112']},
 {'path': '../../data/endf-b8.1/neutron/Ag113.h5',
  'type': 'neutron',
  'materials': ['Ag113']},
 {'path': '../../data/endf-b8.1/neutron/Ag114.h5',
  'type': 'neutron',
  'materials': ['Ag114']},
 {'path': '../../data/endf-b8.1/neutron/Ag115.h5',
  'type': 'neutron',
  'materials': ['Ag115']},
 {'path': '../../data/endf-b8.1/neutron/Ag116.h5',
  'type': 'neutron',
  'materials': ['Ag116']},
 {'path': '../../data/endf-b8.1/neutron/Ag117.h5',
  'type': 'neutron',
  'materials': ['Ag117']},
 {'path': '../../data/endf-b8.1/neutron/Ag118_m1.h5',
  'type': 'neutron',
  'materials': ['Ag118_m1']},
 {'path': '../../data/endf-b8.1/neutron/Cd106.h5',
  'type': 'neutron',
  'materials': ['Cd106']},

In [9]:
xs_openmc = pd.DataFrame(library.libraries)
xs_openmc['materials'] = xs_openmc['materials'].map(lambda x: x[0])
xs_openmc['path'] = xs_openmc['path'].map(lambda x: str(Path(x).relative_to(nuc_dat_path)))
xs_openmc = xs_openmc[xs_etree.columns]
xs_openmc

    materials            path     type
0          H1   neutron/H1.h5  neutron
1          H2   neutron/H2.h5  neutron
2          H3   neutron/H3.h5  neutron
3         He3  neutron/He3.h5  neutron
4         He4  neutron/He4.h5  neutron
..        ...             ...      ...
763        Cm    photon/Cm.h5   photon
764        Bk    photon/Bk.h5   photon
765        Cf    photon/Cf.h5   photon
766        Es    photon/Es.h5   photon
767        Fm    photon/Fm.h5   photon

[768 rows x 3 columns]

### Comparison of the three XML interfaces

The three approaches—manual text parsing, Python's `xml.etree.ElementTree`, and OpenMC's `DataLibrary`—produce equivalent tables for the particular `cross_sections.xml` file examined here, after normalizing their representations.

This equivalence is not guaranteed for arbitrary XML files. The manual parser relies on the file's formatting and attribute order. `ElementTree` interprets XML according to its structure, while OpenMC's `DataLibrary` converts certain attributes into Python objects and resolves library paths.

For example, OpenMC represents `materials` as a list and library paths may be resolved relative to the XML file's location. The comparison therefore requires converting these values back into the representation used in the original XML file.

The equality assertions validate the results for this dataset; they do not establish that the three methods are universally interchangeable.

In [10]:
# Confirm `xs_manual`==`xs_etree`==`xs_openmc`:
pd.testing.assert_frame_equal(xs_manual, xs_etree) 
pd.testing.assert_frame_equal(xs_manual, xs_openmc) 
# Rename as `df`, remove dataframes we no longer need.
df = xs_etree
del xs_manual, xs_etree, xs_openmc

## Look inside `HDF5` files
HDF5 files are binary files. HDF is an acronym for *Hierarchical Data Format*.
The [format](https://www.hdfgroup.org/solutions/hdf5/) is cross platform, with no vendor lock-in.
Ways of looking inside:
1. using `h5py`;
2. using [openmc.data.IncidentNeutron.from_hdf5()](https://docs.openmc.org/en/stable/pythonapi/generated/openmc.data.IncidentNeutron.html).

### Using `h5py`

In [11]:
import h5py

# First, try with a single material.
pic = (df['materials']=='Li6') & (df['type']=='neutron')
filename = df.loc[pic, 'path'].iloc[0]

with h5py.File(nuc_dat_path / filename) as ff:
    print(list(ff.keys()))
    ff.visit(print)
# A single nuclide's HDF5 file contains neutron cross sections at multiple temperatures.

['Li6']
Li6
Li6/energy
Li6/energy/0K
Li6/energy/1200K
Li6/energy/2500K
Li6/energy/250K
Li6/energy/294K
Li6/energy/600K
Li6/energy/900K
Li6/kTs
Li6/kTs/1200K
Li6/kTs/2500K
Li6/kTs/250K
Li6/kTs/294K
Li6/kTs/600K
Li6/kTs/900K
Li6/reactions
Li6/reactions/reaction_002
Li6/reactions/reaction_002/0K
Li6/reactions/reaction_002/0K/xs
Li6/reactions/reaction_002/1200K
Li6/reactions/reaction_002/1200K/xs
Li6/reactions/reaction_002/2500K
Li6/reactions/reaction_002/2500K/xs
Li6/reactions/reaction_002/250K
Li6/reactions/reaction_002/250K/xs
Li6/reactions/reaction_002/294K
Li6/reactions/reaction_002/294K/xs
Li6/reactions/reaction_002/600K
Li6/reactions/reaction_002/600K/xs
Li6/reactions/reaction_002/900K
Li6/reactions/reaction_002/900K/xs
Li6/reactions/reaction_002/product_0
Li6/reactions/reaction_002/product_0/distribution_0
Li6/reactions/reaction_002/product_0/distribution_0/angle
Li6/reactions/reaction_002/product_0/distribution_0/angle/energy
Li6/reactions/reaction_002/product_0/distribution_0/angle/mu
Li6/reactions/reaction_002/product_0/yield
Li6/reactions/reaction_032
Li6/reactions/reaction_032/1200K
Li6/reactions/reaction_032/1200K/xs
Li6/reactions/reaction_032/2500K
Li6/reactions/reaction_032/2500K/xs
Li6/reactions/reaction_032/250K
Li6/reactions/reaction_032/250K/xs
Li6/reactions/reaction_032/294K
Li6/reactions/reaction_032/294K/xs
Li6/reactions/reaction_032/600K
Li6/reactions/reaction_032/600K/xs
Li6/reactions/reaction_032/900K
Li6/reactions/reaction_032/900K/xs
Li6/reactions/reaction_032/product_0
Li6/reactions/reaction_032/product_0/distribution_0
Li6/reactions/reaction_032/product_0/distribution_0/applicability
Li6/reactions/reaction_032/product_0/distribution_0/energy
Li6/reactions/reaction_032/product_0/distribution_0/energy_out
Li6/reactions/reaction_032/product_0/distribution_0/mu
Li6/reactions/reaction_032/product_0/yield
Li6/reactions/reaction_041
Li6/reactions/reaction_041/1200K
Li6/reactions/reaction_041/1200K/xs
Li6/reactions/reaction_041/2500K
Li6/reactions/reaction_041/2500K/xs
Li6/reactions/reaction_041/250K
Li6/reactions/reaction_041/250K/xs
Li6/reactions/reaction_041/294K
Li6/reactions/reaction_041/294K/xs
Li6/reactions/reaction_041/600K
Li6/reactions/reaction_041/600K/xs
Li6/reactions/reaction_041/900K
Li6/reactions/reaction_041/900K/xs
Li6/reactions/reaction_041/product_0
Li6/reactions/reaction_041/product_0/distribution_0
Li6/reactions/reaction_041/product_0/distribution_0/applicability
Li6/reactions/reaction_041/product_0/yield
Li6/reactions/reaction_052
Li6/reactions/reaction_052/1200K
Li6/reactions/reaction_052/1200K/xs
Li6/reactions/reaction_052/2500K
Li6/reactions/reaction_052/2500K/xs
Li6/reactions/reaction_052/250K
Li6/reactions/reaction_052/250K/xs
Li6/reactions/reaction_052/294K
Li6/reactions/reaction_052/294K/xs
Li6/reactions/reaction_052/600K
Li6/reactions/reaction_052/600K/xs
Li6/reactions/reaction_052/900K
Li6/reactions/reaction_052/900K/xs
Li6/reactions/reaction_052/product_0
Li6/reactions/reaction_052/product_0/distribution_0
Li6/reactions/reaction_052/product_0/distribution_0/angle
Li6/reactions/reaction_052/product_0/distribution_0/angle/energy
Li6/reactions/reaction_052/product_0/distribution_0/angle/mu
Li6/reactions/reaction_052/product_0/distribution_0/applicability
Li6/reactions/reaction_052/product_0/distribution_0/energy
Li6/reactions/reaction_052/product_0/yield
Li6/reactions/reaction_102
Li6/reactions/reaction_102/1200K
Li6/reactions/reaction_102/1200K/xs
Li6/reactions/reaction_102/2500K
Li6/reactions/reaction_102/2500K/xs
Li6/reactions/reaction_102/250K
Li6/reactions/reaction_102/250K/xs
Li6/reactions/reaction_102/294K
Li6/reactions/reaction_102/294K/xs
Li6/reactions/reaction_102/600K
Li6/reactions/reaction_102/600K/xs
Li6/reactions/reaction_102/900K
Li6/reactions/reaction_102/900K/xs
Li6/reactions/reaction_102/product_0
Li6/reactions/reaction_102/product_0/distribution_0
Li6/reactions/reaction_102/product_0/distribution_0/angle
Li6/reactions/reaction_102/product_0/distribution_0/angle/energy
Li6/reactions/reaction_102/product_0/distribution_0/angle/mu
Li6/reactions/reaction_102/product_0/distribution_0/energy
Li6/reactions/reaction_102/product_0/yield
Li6/reactions/reaction_102/product_1
Li6/reactions/reaction_102/product_1/distribution_0
Li6/reactions/reaction_102/product_1/distribution_0/angle
Li6/reactions/reaction_102/product_1/distribution_0/angle/energy
Li6/reactions/reaction_102/product_1/distribution_0/angle/mu
Li6/reactions/reaction_102/product_1/distribution_0/energy
Li6/reactions/reaction_102/product_1/yield
Li6/reactions/reaction_102/product_2
Li6/reactions/reaction_102/product_2/distribution_0
Li6/reactions/reaction_102/product_2/distribution_0/angle
Li6/reactions/reaction_102/product_2/distribution_0/angle/energy
Li6/reactions/reaction_102/product_2/distribution_0/angle/mu
Li6/reactions/reaction_102/product_2/distribution_0/energy
Li6/reactions/reaction_102/product_2/yield
Li6/reactions/reaction_103
Li6/reactions/reaction_103/1200K
Li6/reactions/reaction_103/1200K/xs
Li6/reactions/reaction_103/2500K
Li6/reactions/reaction_103/2500K/xs
Li6/reactions/reaction_103/250K
Li6/reactions/reaction_103/250K/xs
Li6/reactions/reaction_103/294K
Li6/reactions/reaction_103/294K/xs
Li6/reactions/reaction_103/600K
Li6/reactions/reaction_103/600K/xs
Li6/reactions/reaction_103/900K
Li6/reactions/reaction_103/900K/xs
Li6/reactions/reaction_105
Li6/reactions/reaction_105/1200K
Li6/reactions/reaction_105/1200K/xs
Li6/reactions/reaction_105/2500K
Li6/reactions/reaction_105/2500K/xs
Li6/reactions/reaction_105/250K
Li6/reactions/reaction_105/250K/xs
Li6/reactions/reaction_105/294K
Li6/reactions/reaction_105/294K/xs
Li6/reactions/reaction_105/600K
Li6/reactions/reaction_105/600K/xs
Li6/reactions/reaction_105/900K
Li6/reactions/reaction_105/900K/xs
Li6/reactions/reaction_203
Li6/reactions/reaction_203/1200K
Li6/reactions/reaction_203/1200K/xs
Li6/reactions/reaction_203/2500K
Li6/reactions/reaction_203/2500K/xs
Li6/reactions/reaction_203/250K
Li6/reactions/reaction_203/250K/xs
Li6/reactions/reaction_203/294K
Li6/reactions/reaction_203/294K/xs
Li6/reactions/reaction_203/600K
Li6/reactions/reaction_203/600K/xs
Li6/reactions/reaction_203/900K
Li6/reactions/reaction_203/900K/xs
Li6/reactions/reaction_204
Li6/reactions/reaction_204/1200K
Li6/reactions/reaction_204/1200K/xs
Li6/reactions/reaction_204/2500K
Li6/reactions/reaction_204/2500K/xs
Li6/reactions/reaction_204/250K
Li6/reactions/reaction_204/250K/xs
Li6/reactions/reaction_204/294K
Li6/reactions/reaction_204/294K/xs
Li6/reactions/reaction_204/600K
Li6/reactions/reaction_204/600K/xs
Li6/reactions/reaction_204/900K
Li6/reactions/reaction_204/900K/xs
Li6/reactions/reaction_205
Li6/reactions/reaction_205/1200K
Li6/reactions/reaction_205/1200K/xs
Li6/reactions/reaction_205/2500K
Li6/reactions/reaction_205/2500K/xs
Li6/reactions/reaction_205/250K
Li6/reactions/reaction_205/250K/xs
Li6/reactions/reaction_205/294K
Li6/reactions/reaction_205/294K/xs
Li6/reactions/reaction_205/600K
Li6/reactions/reaction_205/600K/xs
Li6/reactions/reaction_205/900K
Li6/reactions/reaction_205/900K/xs
Li6/reactions/reaction_207
Li6/reactions/reaction_207/1200K
Li6/reactions/reaction_207/1200K/xs
Li6/reactions/reaction_207/2500K
Li6/reactions/reaction_207/2500K/xs
Li6/reactions/reaction_207/250K
Li6/reactions/reaction_207/250K/xs
Li6/reactions/reaction_207/294K
Li6/reactions/reaction_207/294K/xs
Li6/reactions/reaction_207/600K
Li6/reactions/reaction_207/600K/xs
Li6/reactions/reaction_207/900K
Li6/reactions/reaction_207/900K/xs
Li6/reactions/reaction_301
Li6/reactions/reaction_301/1200K
Li6/reactions/reaction_301/1200K/xs
Li6/reactions/reaction_301/2500K
Li6/reactions/reaction_301/2500K/xs
Li6/reactions/reaction_301/250K
Li6/reactions/reaction_301/250K/xs
Li6/reactions/reaction_301/294K
Li6/reactions/reaction_301/294K/xs
Li6/reactions/reaction_301/600K
Li6/reactions/reaction_301/600K/xs
Li6/reactions/reaction_301/900K
Li6/reactions/reaction_301/900K/xs
Li6/reactions/reaction_444
Li6/reactions/reaction_444/1200K
Li6/reactions/reaction_444/1200K/xs
Li6/reactions/reaction_444/2500K
Li6/reactions/reaction_444/2500K/xs
Li6/reactions/reaction_444/250K
Li6/reactions/reaction_444/250K/xs
Li6/reactions/reaction_444/294K
Li6/reactions/reaction_444/294K/xs
Li6/reactions/reaction_444/600K
Li6/reactions/reaction_444/600K/xs
Li6/reactions/reaction_444/900K
Li6/reactions/reaction_444/900K/xs
Li6/reactions/reaction_901
Li6/reactions/reaction_901/1200K
Li6/reactions/reaction_901/1200K/xs
Li6/reactions/reaction_901/2500K
Li6/reactions/reaction_901/2500K/xs
Li6/reactions/reaction_901/250K
Li6/reactions/reaction_901/250K/xs
Li6/reactions/reaction_901/294K
Li6/reactions/reaction_901/294K/xs
Li6/reactions/reaction_901/600K
Li6/reactions/reaction_901/600K/xs
Li6/reactions/reaction_901/900K
Li6/reactions/reaction_901/900K/xs

In [12]:
# Next, loop over all materials
def get_reactions(filename):
    with h5py.File(nuc_dat_path / filename) as ff:
        nuclide_name = list(ff.keys())[0]
        reactions = ff[nuclide_name]['reactions']

        mts = []
        for name in reactions:
            if name.startswith('reaction_'):
                mt = int(name.removeprefix('reaction_'))
                mts.append(mt)

    return sorted(mts)
df['MTs'] = None
pic = df['type']=='neutron'
df.loc[pic, 'MTs'] = df.loc[pic, 'path'].map(lambda x: get_reactions(x))
df

,materials,path,type,MTs
0,H1,neutron/H1.h5,neutron,"[2, 102, 204, 301, 444, 901]"
1,H2,neutron/H2.h5,neutron,"[2, 16, 102, 203, 205, 301, 444, 901]"
2,H3,neutron/H3.h5,neutron,"[2, 16, 204, 301, 444, 901]"
3,He3,neutron/He3.h5,neutron,"[2, 102, 103, 104, 203, 204, 205, 207, 301, 44..."
4,He4,neutron/He4.h5,neutron,"[2, 301, 444, 901]"
...,...,...,...,...
763,Cm,photon/Cm.h5,photon,None
764,Bk,photon/Bk.h5,photon,None
765,Cf,photon/Cf.h5,photon,None
766,Es,photon/Es.h5,photon,None
767,Fm,photon/Fm.h5,photon,None

### Using openmc.data.IncidentNeutron.from_hdf5()

In [13]:
# Demonstrating with just one material.
# Looping through every material would be too CPU-expensive.
library.get_by_material("Li6")

{'path': '../../data/endf-b8.1/neutron/Li6.h5',
 'type': 'neutron',
 'materials': ['Li6']}

In [14]:
pic = (df['materials']=='Li6') & (df['type']=='neutron')
filename = f"{nuc_dat_path}/{df.loc[pic, 'path'].values[0]}"
data = openmc.data.IncidentNeutron.from_hdf5(filename)
mts_openmc = set(data.reactions)
mts_openmc

{np.int64(2),
 np.int64(32),
 np.int64(41),
 np.int64(52),
 np.int64(102),
 np.int64(103),
 np.int64(105),
 np.int64(203),
 np.int64(204),
 np.int64(205),
 np.int64(207),
 np.int64(301),
 np.int64(444),
 np.int64(901)}

In [15]:
# That matches what we compiled (manually) from `HDF5`, in `df`.
mts_hdf5 = set(df.loc[pic, 'MTs'].values[0])
assert mts_openmc == mts_hdf5

### Interpretation of MT numbers

ENDF MT numbers identify different types of nuclear-reaction information. Many correspond to physical reaction channels, such as elastic scattering (MT 2), radiative capture (MT 102), and neutron-induced triton production, (n,t) (MT 105).

However, not every MT identifier represents a distinct physical reaction channel. Some identify derived or processed quantities, including heating or energy-deposition information (MT 301) and damage-energy production (MT 444).

Consequently, the list of MT identifiers stored in an OpenMC HDF5 file should not be interpreted simply as a list of independent physical reactions. It may also contain quantities calculated from or associated with nuclear reactions.

In [16]:
def get_reaction_names(mts):
    if mts is None:
        return None
    return [
        openmc.data.REACTION_NAME.get(mt, 'Unknown')
        for mt in mts
    ]

df['reaction_names'] = df['MTs'].map(get_reaction_names)
df

,materials,path,type,MTs,reaction_names
0,H1,neutron/H1.h5,neutron,"[2, 102, 204, 301, 444, 901]","[(n,elastic), (n,gamma), (n,Xd), heating, dama..."
1,H2,neutron/H2.h5,neutron,"[2, 16, 102, 203, 205, 301, 444, 901]","[(n,elastic), (n,2n), (n,gamma), (n,Xp), (n,Xt..."
2,H3,neutron/H3.h5,neutron,"[2, 16, 204, 301, 444, 901]","[(n,elastic), (n,2n), (n,Xd), heating, damage-..."
3,He3,neutron/He3.h5,neutron,"[2, 102, 103, 104, 203, 204, 205, 207, 301, 44...","[(n,elastic), (n,gamma), (n,p), (n,d), (n,Xp),..."
4,He4,neutron/He4.h5,neutron,"[2, 301, 444, 901]","[(n,elastic), heating, damage-energy, heating-..."
...,...,...,...,...,...
763,Cm,photon/Cm.h5,photon,None,None
764,Bk,photon/Bk.h5,photon,None,None
765,Cf,photon/Cf.h5,photon,None,None
766,Es,photon/Es.h5,photon,None,None
767,Fm,photon/Fm.h5,photon,None,None

## Materials × MT availability

Rows are neutron-data materials and columns are MT numbers.
`True` indicates that the material's HDF5 file contains that MT; `False` indicates it does not.

In [17]:
# Expand the MT lists, then pivot into a material-by-MT presence table.
pic = df['type']=='neutron'
neutron_mts = df.loc[pic, ['materials', 'MTs']]
neutron_mts

    materials                                                MTs
0          H1                       [2, 102, 204, 301, 444, 901]
1          H2              [2, 16, 102, 203, 205, 301, 444, 901]
2          H3                        [2, 16, 204, 301, 444, 901]
3         He3  [2, 102, 103, 104, 203, 204, 205, 207, 301, 44...
4         He4                                 [2, 301, 444, 901]
..        ...                                                ...
552     Es253  [2, 16, 17, 18, 37, 51, 52, 53, 54, 55, 91, 10...
553     Es254  [2, 16, 17, 18, 37, 51, 52, 53, 54, 55, 56, 57...
554  Es254_m1  [2, 16, 17, 18, 37, 51, 52, 53, 54, 55, 56, 57...
555     Es255  [2, 16, 17, 18, 37, 51, 52, 91, 102, 301, 444,...
556     Fm255  [2, 16, 17, 18, 37, 51, 52, 53, 54, 55, 56, 57...

[557 rows x 2 columns]

In [18]:
material_mt_pairs = neutron_mts.explode('MTs')
material_mt_pairs.rename(columns={'MTs': 'MT'}, inplace=True)
material_mt_pairs['MT'] = material_mt_pairs['MT'].astype(int)
material_mt_pairs['available'] = True
material_mt_pairs

    materials   MT  available
0          H1    2       True
0          H1  102       True
0          H1  204       True
0          H1  301       True
0          H1  444       True
..        ...  ...        ...
556     Fm255   91       True
556     Fm255  102       True
556     Fm255  301       True
556     Fm255  444       True
556     Fm255  901       True

[32796 rows x 3 columns]

In [19]:
material_mt_table = material_mt_pairs.pivot_table(
        index='materials', columns='MT', values='available', 
        aggfunc='any', fill_value=False)
material_mt_table

MT,2,3,4,5,11,16,17,18,19,20,...,832,833,834,835,836,837,838,839,849,901
materials,,,,,,,,,,,,,,,,,,,,,
Ac225,True,False,False,False,False,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,True
Ac226,True,False,False,False,False,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,True
Ac227,True,False,False,False,False,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,True
Ag107,True,False,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
Ag108,True,False,False,True,False,True,False,False,False,False,...,True,True,True,True,True,True,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zr92,True,False,False,True,False,True,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
Zr93,True,False,False,True,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
Zr94,True,False,False,True,False,True,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
Zr95,True,False,False,True,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
Zr96,True,False,False,True,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True